
  - ffmpeg
  - unzip
  - cmake
  - numpy
  - pillow
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - opencv
  - pip:
    - torch
    - torchvision
    - torchaudio
    - torchsde
    - einops
    - "transformers>=4.28.1"
    - "tokenizers>=0.13.3"
    - sentencepiece
    - "safetensors>=0.3.0"
    - aiohttp
    - accelerate
    - pyyaml
    - tqdm
    - psutil
    - spandrel
    - soundfile
    - "kornia>=0.7.1"
    - "websocket-client==1.6.3"
    - "diffusers>=0.25.0"
    - "albumentations==1.4.3"
    - imageio
    - joblib
    - pilgram
    - rembg
    - numba
    - numexpr
    - insightface
    - onnx
    - segment-anything
    - piexif
    - "ultralytics!=8.0.177"
    - timm
    - importlib_metadata
    - filelock
    - python-dateutil
    - mediapipe
    - svglib
    - fvcore
    - yapf
    - omegaconf
    - ftfy
    - addict
    - yacs
    - "trimesh[easy]"
    - librosa
    - color-matcher
    - facexlib
    - "open-clip-torch>=2.24.0"
    - "pytorch-lightning>=2.2.1"
    - huggingface_hub
    - facenet_pytorch
    - pyfacer
    - onnxruntime-gpu